fee_mode: static
simulate:
  N_LP: 100
  N_jit: 3
  T: 2000
  basis_half_life: 1
  binom_n: 70
  binom_p: 0.5
  block_time: 5
  cex_heston_kappa: 1.0
  cex_heston_rho: -0.5
  cex_heston_sigma_v: 0.001
  cex_heston_theta: 1.0e-08
  cex_heston_v0: 2.25e-08
  cex_mu: 0.0
  cex_sigma: 0.00015
  cex_sigma_mode: heston
  config_name: test
  f0: 0.0001
  f_max: 0.05
  f_min: 1.0e-05
  fee_cooldown: 0
  fee_half_life: 2
  fee_step_bps_max: 100.0
  fee_step_bps_min: 0.0005
  flash_loan_fee: 0.0001
  initial_binom_N: 450
  initial_total_L: 500000.0
  jit_flash_loan_fee: 0.0001
  k_basis: 0.0005
  k_lvr: 0.1
  k_out_max: 20
  k_out_min: 10
  k_sigma: 1
  light_mode: false
  liquidity_for_gif: false
  liquidity_perc_jit: 0.9
  mint_mu: -1.0
  mint_sigma: 1.5
  n_block_SR_ratio: 100
  narrow_mints_per_second: 0.1
  noise_trades_per_second: 0.16
  p_jit: 1
  passive_burns_per_second: 0.1
  passive_lp_share: 0.5
  passive_mints_per_second: 0.1
  passive_width_pct: 5.0
  passive_width_ticks: null
  plot_max_points: 15000
  seed: 10
  skip_step: 50
  slippage_tolerance: 0.01
  slope_s: 1
  smart_trades_per_second: 0.16
  tau_seconds: 25.0
  theta_SL: 0.2
  theta_T: 1.0
  theta_TP: 0.1
  trader_mean: 2.5
  trader_sigma: 1.5
  verbose: false
  visualize: false
  w_max_ticks: 1774540
  w_min_ticks: 10
