site_name: My Project Docs
theme:
  name: material

nav:
  - Home: docs/README.md
  - Guide:
      - Fee Schedules: docs/fee_schedules.md
      - LVR: docs/LVR_explaination.md
      - LP PnL: docs/LP_PnL.md
      - Hedged/Not Hedged LP PnL: docs/hedged_pnl_vs_lvr_notes.md
  - Results: docs/results.md
