#!/usr/bin/env python3
"""run_multiple.py

Run the ABM simulation N times with different seeds and plot mean ± std bands
for the PnL time series (similar to the PnL panel generated by run.py).

Implements:
- (a) Parallel execution across seeds.
- (b) Auto-include only the agent PnL series that are meaningful for the scenario
      (e.g., hide active LP series when passive_lp_share=1, hide JIT series when
      JIT is disabled).

Outputs:
  abm_results/scenarios/<scenario>/multi_runs/{html,png}/

Example:
  python run_multiple.py --config abm_results/scenarios/test.yml --runs 20 --seed-base 1 --max-workers 8

Notes:
- We call run.simulate() directly (instead of spawning `python run.py`) so that we
  can collect the PnL series in-memory.
- `verbose=False` does not disable run.py's per-run verbose log file (it is
  controlled by light_mode). To avoid clutter, we route each worker's outputs to
  a per-seed temp folder and delete them by default.
"""

from __future__ import annotations

import argparse
import os
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import plotly.graph_objects as go

import run as run_module
from utils import load_simulation_parameters, scenario_output_root


def _silent_tqdm(iterable=None, **kwargs):
    """Silence tqdm inside run.simulate to avoid nested progress bars."""
    if iterable is None:
        total = int(kwargs.get("total", 0))
        return range(total)
    return iterable


# Monkeypatch tqdm used inside run.py
run_module.tqdm = _silent_tqdm  # type: ignore[attr-defined]

simulate = run_module.simulate
save_plotly_figure = run_module.save_plotly_figure


@dataclass(frozen=True)
class PnlSeriesSpec:
    key: str
    label: str
    color: str
    dash: Optional[str] = None


# Base set (run.py "Agent PnL" panel). We'll filter this list based on config.
BASE_PNL_SPECS: Tuple[PnlSeriesSpec, ...] = (
    PnlSeriesSpec("smart_router_pnl_cum", "Smart router PnL", "#1f77b4", None),
    PnlSeriesSpec("noise_trader_pnl_cum", "Noise trader PnL", "#ff7f0e", "dash"),
    PnlSeriesSpec("arb_pnl_cum", "Arbitrageur PnL", "#2ca02c", None),
    PnlSeriesSpec("lp_pnl_active", "Active LP hedged (fees - LVR)", "#9467bd", "dash"),
    PnlSeriesSpec("jiter_pnl_series", "Jiter hedged net (fees - LVR - flash)", "#d62728", None),
    PnlSeriesSpec("lp_pnl_passive", "Passive LP hedged (fees - LVR)", "#8c564b", "dot"),
)


def _slice_series(values: Sequence[float], skip: int) -> np.ndarray:
    arr = np.asarray(values, dtype=float)
    if arr.size == 0:
        return arr
    s0 = max(0, min(int(skip), int(arr.size)))
    return arr[s0:]


def _hex_to_rgb(hex_color: str) -> Tuple[int, int, int]:
    s = str(hex_color).strip()
    if s.startswith("#"):
        s = s[1:]
    if len(s) != 6:
        raise ValueError(f"Expected #RRGGBB hex color, got {hex_color!r}")
    r = int(s[0:2], 16)
    g = int(s[2:4], 16)
    b = int(s[4:6], 16)
    return r, g, b


def _add_mean_std_band(
    fig: go.Figure,
    *,
    x: np.ndarray,
    mean: np.ndarray,
    std: np.ndarray,
    name: str,
    color: str,
    dash: Optional[str],
    band_alpha: float = 0.18,
) -> None:
    lower = mean - std
    upper = mean + std

    r, g, b = _hex_to_rgb(color)
    fill = f"rgba({r},{g},{b},{band_alpha})"

    # Lower bound (invisible legend)
    fig.add_trace(
        go.Scatter(
            x=x,
            y=lower,
            mode="lines",
            line=dict(width=0),
            showlegend=False,
            hoverinfo="skip",
        )
    )
    # Upper bound, filled down to lower
    fig.add_trace(
        go.Scatter(
            x=x,
            y=upper,
            mode="lines",
            line=dict(width=0),
            fill="tonexty",
            fillcolor=fill,
            showlegend=False,
            hoverinfo="skip",
            name=f"{name} ±1σ",
        )
    )

    line = dict(width=2, color=color)
    if dash:
        line["dash"] = dash

    # Mean line (legend entry)
    fig.add_trace(
        go.Scatter(
            x=x,
            y=mean,
            mode="lines",
            name=f"{name} (mean)",
            line=line,
        )
    )


def _resolve_pnl_specs(params: Dict[str, Any]) -> List[PnlSeriesSpec]:
    """Filter BASE_PNL_SPECS based on which agent cohorts exist in this scenario."""
    try:
        passive_share = float(params.get("passive_lp_share", 1.0))
    except (TypeError, ValueError):
        passive_share = 1.0
    passive_share = max(0.0, min(1.0, passive_share))

    # JIT enabled iff all three are strictly positive.
    try:
        p_jit = float(params.get("p_jit", 0.0))
    except (TypeError, ValueError):
        p_jit = 0.0
    try:
        n_jit = int(params.get("N_jit", 0))
    except (TypeError, ValueError):
        n_jit = 0
    try:
        liq_perc = float(params.get("liquidity_perc_jit", 0.0))
    except (TypeError, ValueError):
        liq_perc = 0.0

    include_active = passive_share < 1.0
    include_passive = passive_share > 0.0
    include_jit = p_jit > 0.0 and n_jit > 0 and liq_perc > 0.0

    specs: List[PnlSeriesSpec] = []
    for spec in BASE_PNL_SPECS:
        if spec.key == "lp_pnl_active" and not include_active:
            continue
        if spec.key == "lp_pnl_passive" and not include_passive:
            continue
        if spec.key == "jiter_pnl_series" and not include_jit:
            continue
        specs.append(spec)
    return specs


def _run_one_seed(
    seed: int,
    *,
    base_params: Dict[str, Any],
    tmp_root: Path,
    keep_run_artifacts: bool,
) -> Dict[str, Any]:
    """Worker function. Returns sliced PnL series for this seed."""
    # Import inside worker to avoid any weird cross-process global state.
    import run as _run_module

    _run_module.tqdm = _silent_tqdm  # type: ignore[attr-defined]

    params = dict(base_params)
    # Pop internal key before calling simulate (it doesn't accept it).
    pnl_keys = params.pop("_pnl_keys", [])
    params["seed"] = int(seed)

    run_dir = tmp_root / f"seed_{int(seed)}"
    run_dir.mkdir(parents=True, exist_ok=True)
    params["results_root"] = run_dir

    out = _run_module.simulate(**params)

    # Slice series after skip_step (same idea as run.py visualization skip)
    skip_step = int(params.get("skip_step", 0))

    payload: Dict[str, Any] = {"seed": int(seed)}
    for key in pnl_keys:
        payload[key] = _slice_series(out.get(key, []), skip_step)

    if not keep_run_artifacts:
        shutil.rmtree(run_dir, ignore_errors=True)

    return payload


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Run N seeds and plot mean±std PnL bands.")
    p.add_argument("--config", required=True, type=Path, help="Path to the YAML scenario config.")
    p.add_argument("--runs", type=int, default=10, help="Number of runs/seeds.")
    p.add_argument(
        "--seed-base",
        type=int,
        default=None,
        help="Base seed (defaults to the YAML seed). Seeds are seed_base + i*seed_step.",
    )
    p.add_argument("--seed-step", type=int, default=1, help="Seed increment per run.")
    p.add_argument(
        "--max-workers",
        type=int,
        default=max(1, (os.cpu_count() or 1) - 1),
        help="Number of parallel worker processes.",
    )
    p.add_argument(
        "--keep-run-artifacts",
        action="store_true",
        help="Keep per-run temp folders/logs under multi_runs/_tmp_runs.",
    )
    p.add_argument(
        "--band-sigma-mult",
        type=float,
        default=1.0,
        help="Shaded band = ±mult*std.",
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()

    if args.runs <= 0:
        raise SystemExit("--runs must be positive.")
    if args.seed_step <= 0:
        raise SystemExit("--seed-step must be positive.")
    if args.max_workers <= 0:
        raise SystemExit("--max-workers must be positive.")

    config_path = args.config.expanduser().resolve()

    scenario_label, base_params = load_simulation_parameters(config_path, simulate_func=simulate)
    base_params = dict(base_params)

    # We need PnL series => light_mode must be False.
    base_params["light_mode"] = False
    # Avoid per-run plots; we only want the aggregated plot.
    base_params["visualize"] = False
    # Reduce stdout, but note: run.py still writes a verbose log file unless light_mode=True.
    base_params["verbose"] = False

    # Decide which PnL series to include.
    pnl_specs = _resolve_pnl_specs(base_params)
    pnl_keys = [spec.key for spec in pnl_specs]
    if not pnl_keys:
        raise SystemExit("No PnL series selected; check your config.")

    # Stash keys into params so worker can avoid pickling specs objects.
    base_params["_pnl_keys"] = pnl_keys

    skip_step = int(base_params.get("skip_step", 0))
    fee_mode = str(base_params.get("fee_mode")).lower()
    seed0 = int(args.seed_base) if args.seed_base is not None else int(base_params.get("seed", 1))
    seeds = [int(seed0 + i * int(args.seed_step)) for i in range(int(args.runs))]

    scenario_root = scenario_output_root(config_path)
    out_root = scenario_root / "multi_runs"
    png_dir = out_root / "png"
    html_dir = out_root / "html"
    png_dir.mkdir(parents=True, exist_ok=True)
    html_dir.mkdir(parents=True, exist_ok=True)

    tmp_root = out_root / "_tmp_runs"
    if tmp_root.exists() and not args.keep_run_artifacts:
        shutil.rmtree(tmp_root, ignore_errors=True)
    tmp_root.mkdir(parents=True, exist_ok=True)

    # --- parallel execution -------------------------------------------------
    from concurrent.futures import ProcessPoolExecutor, as_completed
    from tqdm import tqdm

    results: List[Dict[str, Any]] = []
    with ProcessPoolExecutor(max_workers=int(args.max_workers)) as executor:
        futures = [
            executor.submit(
                _run_one_seed,
                seed,
                base_params=base_params,
                tmp_root=tmp_root,
                keep_run_artifacts=bool(args.keep_run_artifacts),
            )
            for seed in seeds
        ]

        with tqdm(total=len(futures), desc="Seeds", unit="run") as pbar:
            for fut in as_completed(futures):
                results.append(fut.result())
                pbar.update(1)

    # Reorder results by seed for consistent output.
    results.sort(key=lambda r: int(r.get("seed", 0)))

    # Align all series to the minimum length after skip_step.
    min_len: Optional[int] = None
    for key in pnl_keys:
        lens = [int(r[key].size) for r in results if isinstance(r.get(key), np.ndarray)]
        if not lens:
            continue
        cur = min(lens)
        min_len = cur if min_len is None else min(min_len, cur)

    if min_len is None or min_len <= 0:
        raise SystemExit("No usable PnL data collected (check skip_step/light_mode/config).")

    x = np.arange(skip_step, skip_step + int(min_len), dtype=int)

    fig = go.Figure()
    fig.add_hline(y=0.0, line=dict(color="gray", width=1, dash="dot"))

    mult = float(args.band_sigma_mult)
    for spec in pnl_specs:
        mats = np.stack([r[spec.key][:min_len] for r in results], axis=0)
        mean = np.mean(mats, axis=0)
        std = np.std(mats, axis=0) * mult
        _add_mean_std_band(
            fig,
            x=x,
            mean=mean,
            std=2*std,
            name=spec.label,
            color=spec.color,
            dash=spec.dash,
        )

    fig.update_layout(
        template="plotly_white",
        title=(
            f"Agent PnL (token1) — mean ± 2σ across {args.runs} seeds "
            f"({scenario_label})"
        ),
        xaxis_title="Step",
        yaxis_title="Token1 value",
        legend=dict(orientation="h", yanchor="bottom", y=1.02, x=0),
    )

    stem = config_path.stem
    base_name = (
        f"multi_pnl_mean_std_{fee_mode}_{stem}_runs{args.runs}_seed{seed0}_step{args.seed_step}_skip{skip_step}"
    )
    png_path = png_dir / f"{base_name}_{os.getpid()}.png"
    html_path = html_dir / f"{base_name}_{os.getpid()}.html"
    save_plotly_figure(fig, png_path, html_path, source="run_multiple")

    print(f"[multi_runs] scenario: {scenario_label}")
    print(f"[multi_runs] seeds:    {seeds[0]}..{seeds[-1]} (n={len(seeds)})")
    print(f"[multi_runs] series:   {', '.join([s.key for s in pnl_specs])}")
    print(f"[multi_runs] wrote:    {html_path}")
    print(f"[multi_runs] wrote:    {png_path} (requires kaleido for PNG export)")


if __name__ == "__main__":
    main()
