#!/usr/bin/env python3
"""scripts/run_multiple.py

Run the ABM simulation N times with different seeds and plot mean ± std bands
for the PnL time series (similar to the PnL panel generated by scripts/run.py).

Implements:
- (a) Parallel execution across seeds.
- (b) Auto-include only the agent PnL series that are meaningful for the scenario
      (e.g., hide active LP series when passive_lp_share=1, hide JIT series when
      JIT is disabled, hide smart/noise routers when their trades_per_block are 0).

Outputs:
  abm_results/scenarios/<scenario>/multi_runs/<run_id>/<fee_mode>/{html,png}/
  abm_results/scenarios/<scenario>/multi_runs/<run_id>/summary.csv
  abm_results/scenarios/<scenario>/multi_runs/<run_id>/metadata.json

Example:
  python -m scripts.run_multiple --config configs/scenarios/section4_microstructure_model0_static.yml --runs 20 --seed-base 1 --max-workers 8

Notes:
- We call scripts.run.simulate() directly (instead of spawning `python -m scripts.run`) so that we
  can collect the PnL series in-memory.
- `verbose=False` does not disable scripts/run.py's per-run verbose log file (it is
  controlled by light_mode). To avoid clutter, we route each worker's outputs to
  a per-seed temp folder (scoped under a per-invocation PID folder) and delete
  them by default.
"""

from __future__ import annotations

import argparse
import os
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Allow `python scripts/run_multiple.py ...` to work from any CWD by ensuring the
# repo root (parent of `scripts/`) is on `sys.path` so `import core` succeeds.
_REPO_ROOT = Path(__file__).resolve().parents[1]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from scripts import run as run_module
from core.utils import load_simulation_parameters, scenario_output_root
from core.artifacts import (
    build_run_manifest,
    make_unique_dir,
    safe_tag,
    snapshot_file,
    write_csv_rows,
    write_json,
)


def _silent_tqdm(iterable=None, **kwargs):
    """Silence tqdm inside scripts.run.simulate to avoid nested progress bars."""
    if iterable is None:
        total = int(kwargs.get("total", 0))
        return range(total)
    return iterable


# Monkeypatch tqdm used inside scripts/run.py
run_module.tqdm = _silent_tqdm  # type: ignore[attr-defined]

simulate = run_module.simulate
save_plotly_figure = run_module.save_plotly_figure


@dataclass(frozen=True)
class PnlSeriesSpec:
    key: str
    label: str
    color: str
    dash: Optional[str] = None


# Base set (scripts/run.py "Agent PnL" panel). We'll filter this list based on config.
BASE_PNL_SPECS: Tuple[PnlSeriesSpec, ...] = (
    PnlSeriesSpec("smart_router_pnl_cum", "Smart router PnL", "#1f77b4", None),
    PnlSeriesSpec("noise_trader_pnl_cum", "Noise trader PnL", "#ff7f0e", "dash"),
    PnlSeriesSpec("arb_pnl_cum", "Arbitrageur PnL", "#2ca02c", None),
    PnlSeriesSpec("lp_pnl_active", "Active LP hedged", "#9467bd", "dash"),
    PnlSeriesSpec("jiter_pnl_series", "Jiter hedged", "#d62728", None),
    PnlSeriesSpec("lp_pnl_passive", "Passive LP hedged", "#8c564b", "dot"),
)


def _slice_series(values: Sequence[float], skip: int) -> np.ndarray:
    arr = np.asarray(values, dtype=float)
    if arr.size == 0:
        return arr
    s0 = max(0, min(int(skip), int(arr.size)))
    return arr[s0:]


def _slice_sr_dex_share(values: Sequence[float], steps: Sequence[int], skip: int) -> np.ndarray:
    arr = np.asarray(values, dtype=float)
    if arr.size == 0 or int(skip) <= 0:
        return arr
    steps_arr = np.asarray(steps, dtype=int)
    if steps_arr.size != arr.size:
        # Fallback: keep all values if step alignment is unclear.
        return arr
    return arr[steps_arr >= int(skip)]


def _concat_series(results: Sequence[Dict[str, Any]], key: str) -> np.ndarray:
    series = [
        r[key]
        for r in results
        if isinstance(r.get(key), np.ndarray) and r[key].size > 0
    ]
    if not series:
        return np.array([], dtype=float)
    return np.concatenate(series, axis=0)


def _add_quartile_legend_traces(
    fig: go.Figure,
    *,
    values: np.ndarray,
    label_prefix: str,
    color: str,
    row: int,
    col: int,
) -> None:
    arr = np.asarray(values, dtype=float)
    arr = arr[np.isfinite(arr)]
    if arr.size == 0:
        return
    q1, q2, q3 = np.percentile(arr, [25.0, 50.0, 75.0])
    styles = [
        ("Q1", q1, "dash"),
        ("Median", q2, None),
        ("Q3", q3, "dot"),
    ]
    for label, value, dash in styles:
        line = dict(color=color, width=2)
        if dash:
            line["dash"] = dash
        fig.add_trace(
            go.Scatter(
            x=[0, 1],
            y=[0, 1],
            mode="lines",
            line=line,
            name=f"{label_prefix} {label} = {value:.6g}",
            hoverinfo="skip",
            visible="legendonly",
            showlegend=True,
            ),
            row=row,
            col=col,
        )
        fig.update_layout(
            legend=dict(font=dict(size=18, color="black")),
            font=dict(size=18, color="black")
        )


def _hex_to_rgb(hex_color: str) -> Tuple[int, int, int]:
    s = str(hex_color).strip()
    if s.startswith("#"):
        s = s[1:]
    if len(s) != 6:
        raise ValueError(f"Expected #RRGGBB hex color, got {hex_color!r}")
    r = int(s[0:2], 16)
    g = int(s[2:4], 16)
    b = int(s[4:6], 16)
    return r, g, b


def _add_mean_std_band(
    fig: go.Figure,
    *,
    x: np.ndarray,
    mean: np.ndarray,
    std: np.ndarray,
    name: str,
    color: str,
    dash: Optional[str],
    band_alpha: float = 0.18,
) -> None:
    lower = mean - std
    upper = mean + std

    r, g, b = _hex_to_rgb(color)
    fill = f"rgba({r},{g},{b},{band_alpha})"

    # Lower bound (invisible legend)
    fig.add_trace(
        go.Scatter(
            x=x,
            y=lower,
            mode="lines",
            line=dict(width=0),
            showlegend=False,
            hoverinfo="skip",
        )
    )
    # Upper bound, filled down to lower
    fig.add_trace(
        go.Scatter(
            x=x,
            y=upper,
            mode="lines",
            line=dict(width=0),
            fill="tonexty",
            fillcolor=fill,
            showlegend=False,
            hoverinfo="skip",
            name=f"{name} ±1σ",
        )
    )

    line = dict(width=2, color=color)
    if dash:
        line["dash"] = dash

    # Mean line (legend entry)
    fig.add_trace(
        go.Scatter(
            x=x,
            y=mean,
            mode="lines",
            name=f"{name}",
            line=line,
        )
    )

    fig.update_layout(
    legend=dict(
        font=dict(size=18),
        itemsizing="constant",  # prevents shrinking with many traces
        itemwidth=50            # horizontal spacing for each item
    )
)


def _resolve_pnl_specs(params: Dict[str, Any]) -> List[PnlSeriesSpec]:
    """Filter BASE_PNL_SPECS based on which agent cohorts exist in this scenario."""
    try:
        # Accept both spellings to match different configs.
        passive_share = float(params.get("passive_lp_share", params.get("lp_passive_share", 1.0)))
    except (TypeError, ValueError):
        passive_share = 1.0
    passive_share = max(0.0, min(1.0, passive_share))

    try:
        smart_raw = params.get("smart_trades_per_second", None)
        if smart_raw is None:
            smart_raw = params.get("smart_trades_per_block", 0.0)
        smart_trades = float(smart_raw)
    except (TypeError, ValueError):
        smart_trades = 0.0
    try:
        noise_raw = params.get("noise_trades_per_second", None)
        if noise_raw is None:
            noise_raw = params.get("noise_trades_per_block", 0.0)
        noise_trades = float(noise_raw)
    except (TypeError, ValueError):
        noise_trades = 0.0

    # JIT enabled iff all three are strictly positive.
    try:
        p_jit = float(params.get("p_jit", 0.0))
    except (TypeError, ValueError):
        p_jit = 0.0
    try:
        n_jit = int(params.get("N_jit", 0))
    except (TypeError, ValueError):
        n_jit = 0
    try:
        liq_perc = float(params.get("liquidity_perc_jit", 0.0))
    except (TypeError, ValueError):
        liq_perc = 0.0

    include_active = passive_share < 1.0
    include_passive = passive_share > 0.0
    include_jit = p_jit > 0.0 and n_jit > 0 and liq_perc > 0.0
    # Only plot cohorts that actually generate trades/PnL in this scenario.
    include_smart_router = smart_trades > 0.0
    include_noise_trader = noise_trades > 0.0

    specs: List[PnlSeriesSpec] = []
    for spec in BASE_PNL_SPECS:
        if spec.key == "lp_pnl_active" and not include_active:
            continue
        if spec.key == "lp_pnl_passive" and not include_passive:
            continue
        if spec.key == "jiter_pnl_series" and not include_jit:
            continue
        if spec.key == "smart_router_pnl_cum" and not include_smart_router:
            continue
        if spec.key == "noise_trader_pnl_cum" and not include_noise_trader:
            continue
        specs.append(spec)
    return specs


def _run_one_seed(
    seed: int,
    *,
    base_params: Dict[str, Any],
    tmp_root: Path,
    keep_run_artifacts: bool,
) -> Dict[str, Any]:
    """Worker function. Returns sliced PnL series for this seed."""
    # Import inside worker to avoid any weird cross-process global state.
    from scripts import run as _run_module

    _run_module.tqdm = _silent_tqdm  # type: ignore[attr-defined]

    params = dict(base_params)
    # Pop internal key before calling simulate (it doesn't accept it).
    pnl_keys = params.pop("_pnl_keys", [])
    extra_series_keys = params.pop("_extra_series_keys", [])
    params["seed"] = int(seed)

    run_dir = tmp_root / f"seed_{int(seed)}"
    run_dir.mkdir(parents=True, exist_ok=True)
    params["results_root"] = run_dir

    out = _run_module.simulate(**params)

    # Slice series after skip_step (same idea as scripts/run.py visualization skip)
    skip_step = int(params.get("skip_step", 0))

    payload: Dict[str, Any] = {"seed": int(seed)}
    for key in pnl_keys:
        payload[key] = _slice_series(out.get(key, []), skip_step)

    for key in extra_series_keys:
        if key == "fee_series":
            payload[key] = _slice_series(out.get(key, []), skip_step)
        elif key == "smart_router_dex_share_series":
            payload[key] = _slice_sr_dex_share(
                out.get("smart_router_dex_share_series", []),
                out.get("smart_router_dex_share_steps", []),
                skip_step,
            )

    def _sum_counts(values: Any) -> int:
        if isinstance(values, (list, tuple, np.ndarray)):
            return int(np.sum(values))
        return 0

    smart_cex = int(
        out.get("smart_router_swaps_cex_routed", _sum_counts(out.get("smart_router_cex_exec_count", [])))
    )
    smart_dex = int(
        out.get("smart_router_swaps_dex_routed", _sum_counts(out.get("smart_router_dex_exec_count", [])))
    )
    smart_total = out.get("total_smart_router_swaps")
    if smart_total is None:
        smart_total = smart_cex + smart_dex
        if smart_total == 0:
            smart_total = _sum_counts(out.get("smart_router_exec_count", []))

    payload["total_smart_router_swaps"] = int(smart_total)
    payload["smart_router_swaps_cex_routed"] = int(smart_cex)
    payload["smart_router_swaps_dex_routed"] = int(smart_dex)
    payload["smart_router_swaps_rejected_slippage"] = int(out.get("smart_router_swaps_rejected_slippage", 0))

    payload["total_noise_trader_swaps"] = int(
        out.get("total_noise_trader_swaps", _sum_counts(out.get("noise_trader_exec_count", [])))
    )
    payload["noise_trader_swaps_rejected_slippage"] = int(out.get("noise_trader_swaps_rejected_slippage", 0))

    payload["total_arb_swaps"] = int(out.get("total_arb_swaps", _sum_counts(out.get("arb_exec_count", []))))
    payload["arb_no_op_in_band"] = int(out.get("arb_no_op_in_band", 0))
    payload["arb_swaps_rejected_profitability"] = int(out.get("arb_swaps_rejected_profitability", 0))
    payload["total_jit_trades_executed"] = int(out.get("total_jit_trades_executed", 0))

    if not keep_run_artifacts:
        shutil.rmtree(run_dir, ignore_errors=True)

    return payload


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments for multi-run simulations.

    Parameters:
        None.

    Returns:
        argparse.Namespace: Parsed CLI options for run_multiple.

    Notes:
        Reads from sys.argv and applies default values defined in this module.

    Examples:
        >>> args = parse_args()
    """
    valid_fee_modes = ("static", "toxicity", "volatility_cex", "volatility_dex")
    p = argparse.ArgumentParser(description="Run N seeds and plot mean±std PnL bands.")
    p.add_argument("--config", required=True, type=Path, help="Path to the YAML scenario config. Required.")
    p.add_argument("--runs", type=int, default=10, help="Number of runs/seeds. Default is 10.")
    p.add_argument(
        "--seed-base",
        type=int,
        default=None,
        help="Base seed (defaults to the YAML seed). Seeds are seed_base + i*seed_step.",
    )
    p.add_argument("--seed-step", type=int, default=1, help="Seed increment per run.")
    p.add_argument(
        "--max-workers",
        type=int,
        default=max(1, (os.cpu_count() or 1) - 1),
        help="Number of parallel worker processes. Defaults to number of CPUs minus one.",
    )
    p.add_argument(
        "--keep-run-artifacts",
        action="store_true",
        help=(
            "Keep per-run temp folders/logs under multi_runs/_tmp_runs/<pid>/... "
            "Default is to delete them."
        ),
    )
    p.add_argument(
        "--band-sigma-mult",
        type=float,
        default=2.0,
        help="Shaded band = ±mult*std. Default 2.0 (±2σ).",
    )
    p.add_argument(
        "--fee-modes",
        nargs="+",
        default=list(valid_fee_modes),
        choices=list(valid_fee_modes),
        help=(
            "Fee modes to run. Provide one or more values. "
            "Default runs all supported modes."
        ),
    )
    return p.parse_args()


def main() -> None:
    """Run multi-seed simulations and write aggregated outputs.

    Parameters:
        None.

    Returns:
        None.

    Notes:
        Writes plots and a trade-summary log under the scenario's multi_runs folder.

    Examples:
        >>> main()
    """
    args = parse_args()

    if args.runs <= 0:
        raise SystemExit("--runs must be positive.")
    if args.seed_step <= 0:
        raise SystemExit("--seed-step must be positive.")
    if args.max_workers <= 0:
        raise SystemExit("--max-workers must be positive.")

    print("PID:", os.getpid())
    config_path = args.config.expanduser().resolve()

    _, base_params = load_simulation_parameters(config_path, simulate_func=simulate)
    base_params = dict(base_params)

    fee_modes = [str(mode).lower() for mode in args.fee_modes]

    scenario_root = scenario_output_root(config_path)
    out_root = scenario_root / "multi_runs"
    out_root.mkdir(parents=True, exist_ok=True)

    # Stable invocation id (deterministic base; uniqueness handled via suffix).
    seed0 = int(args.seed_base) if args.seed_base is not None else int(base_params.get("seed", 1))
    invocation_id_base = safe_tag(
        f"{config_path.stem}_runs{int(args.runs)}_seed{seed0}_step{int(args.seed_step)}"
    )
    invocation_root = make_unique_dir(out_root / invocation_id_base)

    snapshot_file(config_path, invocation_root / "config_snapshot.yml")
    manifest = build_run_manifest(script="run_multiple", run_id=invocation_root.name, config_path=config_path)
    write_json(
        invocation_root / "metadata.json",
        {
            **manifest.to_dict(),
            "fee_modes": list(fee_modes),
            "runs": int(args.runs),
            "seed_base": int(seed0),
            "seed_step": int(args.seed_step),
            "max_workers": int(args.max_workers),
            "config_stem": str(config_path.stem),
        },
    )

    # Use a per-invocation temp root to avoid collisions across concurrent runs.
    run_tmp_root = make_unique_dir(invocation_root / "_tmp_runs")

    base_params_common = dict(base_params)
    # We need PnL series => light_mode must be False.
    base_params_common["light_mode"] = False
    # Avoid per-run plots; we only want the aggregated plot.
    base_params_common["visualize"] = False
    # Reduce stdout; note: scripts/run.py still writes a verbose log file unless light_mode=True.
    base_params_common["verbose"] = False

    summary_rows: List[Dict[str, Any]] = []

    for fee_mode in fee_modes:
        print(f"[multi_runs] Generating runs for fee_mode={fee_mode}...")
        mode_root = invocation_root / safe_tag(fee_mode)
        png_dir = mode_root / "png"
        html_dir = mode_root / "html"
        png_dir.mkdir(parents=True, exist_ok=True)
        html_dir.mkdir(parents=True, exist_ok=True)

        params = dict(base_params_common)
        params["fee_mode"] = str(fee_mode)

        # Decide which PnL series to include.
        pnl_specs = _resolve_pnl_specs(params)
        pnl_keys = [spec.key for spec in pnl_specs]
        if not pnl_keys:
            raise SystemExit("No PnL series selected; check your config.")

        # Stash keys into params so worker can avoid pickling specs objects.
        params["_pnl_keys"] = pnl_keys
        params["_extra_series_keys"] = ["fee_series", "smart_router_dex_share_series"]

        skip_step = int(params.get("skip_step", 0))
        seeds = [int(seed0 + i * int(args.seed_step)) for i in range(int(args.runs))]

        # Separate fee modes within the same invocation to avoid overwriting artifacts
        # when --keep-run-artifacts is enabled.
        tmp_root = run_tmp_root / safe_tag(str(fee_mode))
        tmp_root.mkdir(parents=True, exist_ok=True)

        # --- parallel execution -------------------------------------------------
        from concurrent.futures import ProcessPoolExecutor, as_completed
        from tqdm import tqdm

        results: List[Dict[str, Any]] = []
        with ProcessPoolExecutor(max_workers=int(args.max_workers)) as executor:
            futures = [
                executor.submit(
                    _run_one_seed,
                    seed,
                    base_params=params,
                    tmp_root=tmp_root,
                    keep_run_artifacts=bool(args.keep_run_artifacts),
                )
                for seed in seeds
            ]

            with tqdm(total=len(futures), desc="Seeds", unit="run") as pbar:
                for fut in as_completed(futures):
                    results.append(fut.result())
                    pbar.update(1)

        # Reorder results by seed for consistent output.
        results.sort(key=lambda r: int(r.get("seed", 0)))

        total_smart_router_swaps = sum(int(r.get("total_smart_router_swaps", 0)) for r in results)
        total_smart_router_swaps_cex = sum(int(r.get("smart_router_swaps_cex_routed", 0)) for r in results)
        total_smart_router_swaps_dex = sum(int(r.get("smart_router_swaps_dex_routed", 0)) for r in results)
        total_smart_router_rejected = sum(
            int(r.get("smart_router_swaps_rejected_slippage", 0)) for r in results
        )

        total_noise_trader_swaps = sum(int(r.get("total_noise_trader_swaps", 0)) for r in results)
        total_noise_trader_rejected = sum(
            int(r.get("noise_trader_swaps_rejected_slippage", 0)) for r in results
        )

        total_arb_swaps = sum(int(r.get("total_arb_swaps", 0)) for r in results)
        total_arb_no_op = sum(int(r.get("arb_no_op_in_band", 0)) for r in results)
        total_arb_rejected_profitability = sum(
            int(r.get("arb_swaps_rejected_profitability", 0)) for r in results
        )
        total_jit_trades_executed = sum(int(r.get("total_jit_trades_executed", 0)) for r in results)
        n_runs = max(1, len(results))

        smart_total_arr = np.array(
            [int(r.get("total_smart_router_swaps", 0)) for r in results], dtype=float
        )
        smart_cex_arr = np.array(
            [int(r.get("smart_router_swaps_cex_routed", 0)) for r in results], dtype=float
        )
        smart_dex_arr = np.array(
            [int(r.get("smart_router_swaps_dex_routed", 0)) for r in results], dtype=float
        )
        smart_rejected_arr = np.array(
            [int(r.get("smart_router_swaps_rejected_slippage", 0)) for r in results], dtype=float
        )

        noise_total_arr = np.array(
            [int(r.get("total_noise_trader_swaps", 0)) for r in results], dtype=float
        )
        noise_rejected_arr = np.array(
            [int(r.get("noise_trader_swaps_rejected_slippage", 0)) for r in results], dtype=float
        )

        arb_total_arr = np.array(
            [int(r.get("total_arb_swaps", 0)) for r in results], dtype=float
        )
        arb_no_op_arr = np.array(
            [int(r.get("arb_no_op_in_band", 0)) for r in results], dtype=float
        )
        arb_rejected_arr = np.array(
            [int(r.get("arb_swaps_rejected_profitability", 0)) for r in results], dtype=float
        )

        jit_executed_arr = np.array(
            [int(r.get("total_jit_trades_executed", 0)) for r in results], dtype=float
        )

        smart_total_mean = float(np.mean(smart_total_arr)) if n_runs > 0 else float("nan")
        smart_total_std = float(np.std(smart_total_arr)) if n_runs > 0 else float("nan")
        smart_cex_mean = float(np.mean(smart_cex_arr)) if n_runs > 0 else float("nan")
        smart_cex_std = float(np.std(smart_cex_arr)) if n_runs > 0 else float("nan")
        smart_dex_mean = float(np.mean(smart_dex_arr)) if n_runs > 0 else float("nan")
        smart_dex_std = float(np.std(smart_dex_arr)) if n_runs > 0 else float("nan")
        smart_rejected_mean = float(np.mean(smart_rejected_arr)) if n_runs > 0 else float("nan")
        smart_rejected_std = float(np.std(smart_rejected_arr)) if n_runs > 0 else float("nan")

        noise_total_mean = float(np.mean(noise_total_arr)) if n_runs > 0 else float("nan")
        noise_total_std = float(np.std(noise_total_arr)) if n_runs > 0 else float("nan")
        noise_rejected_mean = float(np.mean(noise_rejected_arr)) if n_runs > 0 else float("nan")
        noise_rejected_std = float(np.std(noise_rejected_arr)) if n_runs > 0 else float("nan")

        arb_total_mean = float(np.mean(arb_total_arr)) if n_runs > 0 else float("nan")
        arb_total_std = float(np.std(arb_total_arr)) if n_runs > 0 else float("nan")
        arb_no_op_mean = float(np.mean(arb_no_op_arr)) if n_runs > 0 else float("nan")
        arb_no_op_std = float(np.std(arb_no_op_arr)) if n_runs > 0 else float("nan")
        arb_rejected_mean = float(np.mean(arb_rejected_arr)) if n_runs > 0 else float("nan")
        arb_rejected_std = float(np.std(arb_rejected_arr)) if n_runs > 0 else float("nan")

        jit_executed_mean = float(np.mean(jit_executed_arr)) if n_runs > 0 else float("nan")
        jit_executed_std = float(np.std(jit_executed_arr)) if n_runs > 0 else float("nan")

        # Align all series to the minimum length after skip_step.
        min_len: Optional[int] = None
        for key in pnl_keys:
            lens = [int(r[key].size) for r in results if isinstance(r.get(key), np.ndarray)]
            if not lens:
                continue
            cur = min(lens)
            min_len = cur if min_len is None else min(min_len, cur)

        if min_len is None or min_len <= 0:
            raise SystemExit("No usable PnL data collected (check skip_step/light_mode/config).")

        x = np.arange(skip_step, skip_step + int(min_len), dtype=int)

        fig = go.Figure()
        fig.add_hline(y=0.0, line=dict(color="gray", width=1, dash="dot"))

        mult = float(args.band_sigma_mult)
        for spec in pnl_specs:
            mats = np.stack([r[spec.key][:min_len] for r in results], axis=0)
            mean = np.mean(mats, axis=0)
            std = np.std(mats, axis=0) * mult
            _add_mean_std_band(
                fig,
                x=x,
                mean=mean,
                std=2*std,
                name=spec.label,
                color=spec.color,
                dash=spec.dash,
            )

        fig.update_layout(
            template="plotly_white",
            title=(
                f"Agents's PnL "
                f"({fee_mode})"
            ),
            xaxis_title="Blocks",
            yaxis_title="Token1 value",
            legend=dict(
                orientation="h",
                yanchor="bottom",
                y=1.02,
                x=0,
                font=dict(size=18, color="black"),
            ),
            font=dict(size=18, color="black"),
            title_font=dict(size=18, color="black"),
            xaxis=dict(title_font=dict(size=18), tickfont=dict(size=18)),
        yaxis=dict(title_font=dict(size=18), tickfont=dict(size=18)),
    )

        stem = config_path.stem
        lp_share_val = base_params.get("passive_lp_share", base_params.get("lp_passive_share", "NA"))
        p_jit_val = base_params.get("p_jit", "NA")
        base_name = (
            f"pnl_{fee_mode}_{stem}_runs{args.runs}_LPpassiveshare{lp_share_val}_pjit{p_jit_val}"
        )
        png_path = png_dir / f"{base_name}_{os.getpid()}.png"
        html_path = html_dir / f"{base_name}_{os.getpid()}.html"
        save_plotly_figure(fig, png_path, html_path, source="run_multiple")

        sr_share_values = _concat_series(results, "smart_router_dex_share_series")
        if str(fee_mode).lower() == "static":
            dist_fig = make_subplots(
                rows=1,
                cols=1,
                subplot_titles=("Smart-router DEX share distribution",),
            )
            dist_fig.add_trace(
                go.Histogram(
                    x=sr_share_values,
                    name="Smart-router DEX share",
                    marker=dict(color="#ff7f0e"),
                    opacity=0.85,
                    showlegend=False,
                ),
                row=1,
                col=1,
            )

            # Mark mean DEX share for quick reference.
            sr_mean = (
                np.mean(sr_share_values[np.isfinite(sr_share_values)])
                if sr_share_values.size
                else None
            )
            if sr_mean is not None and np.isfinite(sr_mean):
                dist_fig.add_shape(
                    type="line",
                    x0=float(sr_mean),
                    x1=float(sr_mean),
                    y0=0,
                    y1=1,
                    # For the first (and only) subplot, Plotly uses "x"/"y"
                    # (not "x1"/"y1") for axis references.
                    xref="x",
                    yref="y domain",
                    line=dict(color="firebrick", width=2, dash="dash"),
                )

            _add_quartile_legend_traces(
                dist_fig,
                values=sr_share_values,
                label_prefix="SR DEX share",
                color="#ff7f0e",
                row=1,
                col=1,
            )

            if sr_share_values.size == 0:
                dist_fig.add_annotation(
                    text="No smart-router DEX share data",
                    showarrow=False,
                    x=0.5,
                    y=0.5,
                    xref="x domain",
                    yref="y domain",
                )

            dist_fig.update_layout(
                template="plotly_white",
                title=dict(
                    text=f"Smart-router DEX share ({fee_mode})",
                    y=0.98,
                    yanchor="top",
                ),
                legend=dict(
                    orientation="h",
                    yanchor="top",
                    y=1.15,
                    xanchor="center",
                    x=0.5,
                    font=dict(size=18, color="black"),
                ),
                font=dict(size=18, color="black"),
                margin=dict(t=180, b=80),
            )
            dist_fig.update_xaxes(title_text="DEX share", row=1, col=1)
            dist_fig.update_yaxes(title_text="Count", row=1, col=1)
        else:
            fee_values = _concat_series(results, "fee_series")

            dist_fig = make_subplots(
                rows=1,
                cols=2,
                subplot_titles=(
                    "Fee distribution",
                    "Smart-router DEX share distribution",
                ),
            )
            dist_fig.add_trace(
                go.Histogram(
                    x=fee_values,
                    name="Fee",
                    marker=dict(color="#1f77b4"),
                    opacity=0.85,
                    showlegend=False,
                ),
                row=1,
                col=1,
            )
            dist_fig.add_trace(
                go.Histogram(
                    x=sr_share_values,
                    name="Smart-router DEX share",
                    marker=dict(color="#ff7f0e"),
                    opacity=0.85,
                    showlegend=False,
                ),
                row=1,
                col=2,
            )
            # Mark mean DEX share for quick reference.
            sr_mean = (
                np.mean(sr_share_values[np.isfinite(sr_share_values)])
                if sr_share_values.size
                else None
            )
            if sr_mean is not None and np.isfinite(sr_mean):
                dist_fig.add_shape(
                    type="line",
                    x0=float(sr_mean),
                    x1=float(sr_mean),
                    y0=0,
                    y1=1,
                    xref="x2",
                    yref="y2 domain",
                    line=dict(color="firebrick", width=2, dash="dash"),
                )

            _add_quartile_legend_traces(
                dist_fig,
                values=fee_values,
                label_prefix="Fee",
                color="#1f77b4",
                row=1,
                col=1,
            )
            _add_quartile_legend_traces(
                dist_fig,
                values=sr_share_values,
                label_prefix="SR DEX share",
                color="#ff7f0e",
                row=1,
                col=2,
            )

            if fee_values.size == 0:
                dist_fig.add_annotation(
                    text="No fee data",
                    showarrow=False,
                    x=0.5,
                    y=0.5,
                    xref="x1 domain",
                    yref="y1 domain",
                )
            if sr_share_values.size == 0:
                dist_fig.add_annotation(
                    text="No smart-router DEX share data",
                    showarrow=False,
                    x=0.5,
                    y=0.5,
                    xref="x2 domain",
                    yref="y2 domain",
                )

            dist_fig.update_layout(
                template="plotly_white",
                title=dict(
                    text=f"Fee and smart-router DEX share ({fee_mode})",
                    y=0.98,
                    yanchor="top",
                ),
                legend=dict(
                    orientation="h",
                    yanchor="top",
                    y=1.15,
                    xanchor="center",
                    x=0.5,
                    font=dict(size=18, color="black"),
                ),
                font=dict(size=18, color="black"),
                margin=dict(t=180, b=80),
            )
            dist_fig.update_xaxes(title_text="Fee", row=1, col=1)
            dist_fig.update_xaxes(title_text="DEX share", row=1, col=2)
            dist_fig.update_yaxes(title_text="Count", row=1, col=1)
            dist_fig.update_yaxes(title_text="Count", row=1, col=2)

        dist_base_name = (
            f"fee_{fee_mode}_{stem}_runs{args.runs}_LPpassiveshare{lp_share_val}_pjit{p_jit_val}"
        )
        dist_png_path = png_dir / f"{dist_base_name}.png"
        dist_html_path = html_dir / f"{dist_base_name}.html"
        save_plotly_figure(dist_fig, dist_png_path, dist_html_path, source="run_multiple")

        log_base_name = (
            f"trade_summary_{fee_mode}_{stem}_runs{args.runs}_LPpassiveshare{lp_share_val}_pjit{p_jit_val}"
        )
        log_path = mode_root / f"{log_base_name}.txt"
        log_lines = [
            "# Multi-run trade summary",
            f"config = {config_path}",
            f"fee_mode = {fee_mode}",
            f"runs = {len(results)}",
            f"seeds = {seeds[0]}..{seeds[-1]} (step={args.seed_step})",
            "---- totals across runs ----",
            f"arb_trades_executed = {total_arb_swaps}",
            f"arb_trades_no_op_in_band = {total_arb_no_op}",
            f"arb_trades_rejected_profitability = {total_arb_rejected_profitability}",
            f"jit_trades_executed = {total_jit_trades_executed}",
            f"noise_trader_trades_executed = {total_noise_trader_swaps}",
            f"noise_trader_trades_rejected_slippage = {total_noise_trader_rejected}",
            f"smart_router_trades_total = {total_smart_router_swaps}",
            f"smart_router_trades_dex = {total_smart_router_swaps_dex}",
            f"smart_router_trades_cex = {total_smart_router_swaps_cex}",
            f"smart_router_trades_rejected_slippage = {total_smart_router_rejected}",
            "---- per-run mean/std ----",
            f"arb_trades_executed_mean = {arb_total_mean:.6f}",
            f"arb_trades_executed_std = {arb_total_std:.6f}",
            f"arb_trades_no_op_in_band_mean = {arb_no_op_mean:.6f}",
            f"arb_trades_no_op_in_band_std = {arb_no_op_std:.6f}",
            f"arb_trades_rejected_profitability_mean = {arb_rejected_mean:.6f}",
            f"arb_trades_rejected_profitability_std = {arb_rejected_std:.6f}",
            f"jit_trades_executed_mean = {jit_executed_mean:.6f}",
            f"jit_trades_executed_std = {jit_executed_std:.6f}",
            f"noise_trader_trades_executed_mean = {noise_total_mean:.6f}",
            f"noise_trader_trades_executed_std = {noise_total_std:.6f}",
            f"noise_trader_trades_rejected_slippage_mean = {noise_rejected_mean:.6f}",
            f"noise_trader_trades_rejected_slippage_std = {noise_rejected_std:.6f}",
            f"smart_router_trades_total_mean = {smart_total_mean:.6f}",
            f"smart_router_trades_total_std = {smart_total_std:.6f}",
            f"smart_router_trades_dex_mean = {smart_dex_mean:.6f}",
            f"smart_router_trades_dex_std = {smart_dex_std:.6f}",
            f"smart_router_trades_cex_mean = {smart_cex_mean:.6f}",
            f"smart_router_trades_cex_std = {smart_cex_std:.6f}",
            f"smart_router_trades_rejected_slippage_mean = {smart_rejected_mean:.6f}",
            f"smart_router_trades_rejected_slippage_std = {smart_rejected_std:.6f}",
            "note = smart_router_trades_total includes CEX + DEX routes",
        ]
        log_path.write_text("\n".join(log_lines) + "\n")

        # Append per-seed summary rows (single table across fee modes).
        for r in results:
            row: Dict[str, Any] = {
                "run_id": invocation_root.name,
                "fee_mode": str(fee_mode),
                "seed": int(r.get("seed", 0)),
                "skip_step": int(skip_step),
            }
            for key in pnl_keys:
                series = r.get(key)
                if isinstance(series, np.ndarray) and series.size > 0:
                    row[f"{key}_final"] = float(series[-1])
                else:
                    row[f"{key}_final"] = float("nan")
            fee_series = r.get("fee_series")
            if isinstance(fee_series, np.ndarray) and fee_series.size > 0:
                row["fee_mean"] = float(np.nanmean(fee_series))
                row["fee_median"] = float(np.nanmedian(fee_series))
            else:
                row["fee_mean"] = float("nan")
                row["fee_median"] = float("nan")
            sr_share = r.get("smart_router_dex_share_series")
            if isinstance(sr_share, np.ndarray) and sr_share.size > 0:
                row["smart_router_dex_share_mean"] = float(np.nanmean(sr_share))
                row["smart_router_dex_share_median"] = float(np.nanmedian(sr_share))
            else:
                row["smart_router_dex_share_mean"] = float("nan")
                row["smart_router_dex_share_median"] = float("nan")

            for key in (
                "total_smart_router_swaps",
                "smart_router_swaps_cex_routed",
                "smart_router_swaps_dex_routed",
                "smart_router_swaps_rejected_slippage",
                "total_noise_trader_swaps",
                "noise_trader_swaps_rejected_slippage",
                "total_arb_swaps",
                "arb_no_op_in_band",
                "arb_swaps_rejected_profitability",
                "total_jit_trades_executed",
            ):
                row[key] = int(r.get(key, 0) or 0)
            summary_rows.append(row)

        print(f"[multi_runs] scenario: {fee_mode}")
        print(f"[multi_runs] seeds:    {seeds[0]}..{seeds[-1]} (n={len(seeds)})")
        print(f"[multi_runs] series:   {', '.join([s.key for s in pnl_specs])}")
        print(f"[multi_runs] wrote:    {html_path}")
        print(f"[multi_runs] wrote:    {png_path} (requires kaleido for PNG export)")
        print(f"[multi_runs] wrote:    {dist_html_path}")
        print(f"[multi_runs] wrote:    {dist_png_path} (requires kaleido for PNG export)")
        print(f"[multi_runs] wrote:    {log_path}")
        print(f"[multi_runs] run dir:  {mode_root}")

    write_csv_rows(invocation_root / "summary.csv", summary_rows)
    print(f"[multi_runs] summary:   {invocation_root / 'summary.csv'}")

    if not args.keep_run_artifacts:
        # Best-effort cleanup of the temp folders created for this invocation.
        # Each worker already deletes its own seed folder; this removes any
        # leftovers (e.g., if a run crashed mid-way).
        shutil.rmtree(run_tmp_root, ignore_errors=True)


if __name__ == "__main__":
    main()
